/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const action1_Logic = require('./code/action1-logic');
const tempdata_Logic = require('./code/tempdata-logic');
const { v4: uuidv4 } = require('uuid'); // UUIDを生成するためにuuidライブラリを使用
class myproject1Service extends LCAPApplicationService {
    async init() {

        this.on('READ', 'TempData', async () => {
            return [{ ID: uuidv4(), Message: 'Test...' }];
        });

        this.on('CREATE', 'TempData', async () => {
            return [{ ID: uuidv4(), Message: 'Test...' }];
        });

        return super.init();
    }
}


module.exports = {
    myproject1Service
};