/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const action1_Logic = require('./code/action1-logic');
const tempdata_Logic = require('./code/tempdata-logic');

class myproject1Service extends LCAPApplicationService {
    async init() {

        this.on('Action1', async (request, next) => {
            return action1_Logic(request);
        });

        this.on(['CREATE', 'READ'], 'TempData', async (request, next) => {
            await tempdata_Logic(request);
            return next();
        });

        return super.init();
    }
}


module.exports = {
    myproject1Service
};